"""File templates and I/O helpers for the repoheart init CLI.

To change what gets generated by `repoheart init`, edit this file only.
"""

from __future__ import annotations

from pathlib import Path

_WORKFLOW_TEMPLATE = """\
name: RepoHeart

on:
  issues:
    types: [opened, edited]

  issue_comment:
    types: [created]

  pull_request:
    types: [opened, synchronize, reopened]

  pull_request_review:
    types: [submitted]

  push:

  workflow_run:
    workflows: ["*"]
    types: [completed]

  release:
    types: [published]

permissions:
  contents: write
  issues: write
  pull-requests: write
  checks: read
  actions: read

concurrency:
  group: repoheart-${{{{ github.event.issue.number || github.event.pull_request.number || github.ref }}}}
  cancel-in-progress: false

jobs:
  repoheart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Run RepoHeart
        uses: OpenAgentHQ/repoheart@main
        with:
          config: repoheart.yml
        env:
          GITHUB_TOKEN: ${{{{ secrets.GITHUB_TOKEN }}}}
          OPENCODE_API_KEY: ${{{{ secrets.OPENCODE_API_KEY }}}}
          ANTHROPIC_API_KEY: ${{{{ secrets.ANTHROPIC_API_KEY }}}}
          OPENAI_API_KEY: ${{{{ secrets.OPENAI_API_KEY }}}}
          GEMINI_API_KEY: ${{{{ secrets.GEMINI_API_KEY }}}}
          OPENROUTER_API_KEY: ${{{{ secrets.OPENROUTER_API_KEY }}}}
"""


def render_workflow() -> str:
    """Return the GitHub Actions workflow YAML string."""
    return _WORKFLOW_TEMPLATE.format()


def render_config(
    provider: str,
    model: str,
    agents: dict[str, bool],
    automation_level: str,
    agent_descriptions: dict[str, str] | None = None,
) -> str:
    """Return a repoheart.yml YAML string for the given choices."""
    desc = agent_descriptions or {}
    agent_lines = "\n".join(
        f"    {name}: {'true' if enabled else 'false'}"
        + (f"  # {desc[name]}" if name in desc else "")
        for name, enabled in agents.items()
    )
    return f"""\
# repoheart.yml — RepoHeart configuration
#
# Generated by `repoheart init`. Edit as needed.
# Only `provider` and at least one enabled agent are required.

repoheart:

  provider:
    name: {provider}
    model: {model}

  agents:
{agent_lines}

  automation:
    level: {automation_level}
    require_human_approval:
      - HIGH
      - MEDIUM

  scale:
    checkout: event-scoped
    retrieval:
      semantic: false
    cache:
      backend: actions
    limits:
      max_llm_calls: 30
      max_files_read: 200
      max_runtime_seconds: 600
"""


def write_file(path: Path, content: str, force: bool) -> None:
    """Write content to path, creating parent directories as needed.

    Raises FileExistsError if path exists and force is False.
    """
    if path.exists() and not force:
        raise FileExistsError(f"{path} already exists. Use --force to overwrite.")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def prompt_or_default(question: str, default: str, yes: bool) -> str:
    """Print question and read input; return default immediately when yes=True."""
    if yes:
        return default
    reply = input(f"{question} [{default}]: ").strip()
    return reply if reply else default
